#!/bin/sh

# small utility to copy dotfiles/src/.* files to ~

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# change to home directory
cd

# create any missing directories
for d in $(find ${root_dir}/src/* -type d); do
	dir=".${d##*/src/}"
	if [ -L $dir ]; then
		rm $dir
	fi
	mkdir -p $dir
done
	
# set symlinks for files
for f in $(find ${root_dir}/src/* -type f,l); do
	l=".${f##*/src/}"
	rm -rf $l
	cp -p $f $l
done
