#!/bin/sh

# small utility to copy dotfiles/src/.* files to ~

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# change to home directory
cd

# copy top level files/directories
for file in $root_dir/src/.[a-zA-Z]*; do
	dfile="$(basename $file)"
	rm -rf $dfile
	cp -rp $file $dfile
done

# copy .config files/directories
for file in $root_dir/config_src/*; do
	dfile=".config/$(basename $file)"
	rm -rf $dfile
	cp -rp $file $dfile
done
