#!/bin/sh

# small utility to establish relative paths to the dotfiles/src/.* files
# DOTFILES_SRC may be set to accomodate alternate locations


cd

DOTFILES_SRC=${DOTFILES_SRC:-"dotfiles/src"}

for file in $DOTFILES_SRC/.[a-zA-Z]*; do
	dfile="$(basename $file)"
	rm -rf $dfile
	ln -s $file $dfile
done
