#!/bin/sh

# small utility to establish relative paths to the dotfiles/src/.* files

root_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# change to home directory
cd

# set symlinks for top level files/directories
for file in $root_dir/src/.[a-zA-Z]*; do
	dfile="$(basename $file)"
	rm -rf $dfile
	ln -s $file $dfile
done

# set symlinks for .config files/directories
for file in $root_dir/config_src/*; do
	dfile=".config/$(basename $file)"
	rm -rf $dfile
	ln -s $file $dfile
done
